<?php
// Copyright 1999-2015. Parallels IP Holdings GmbH.
?>
<p><b>State:</b> <?php echo $this->request->state === '0' ? 'Active' : 'Resolved'; ?></p>
<p><b>Customer:</b>
    <a href="/admin/customer/overview/id/<?php echo $this->request->customer_id; ?>">
        <?php echo $this->client->getProperty('login'); ?></a>
</p>
<p><b>Description:</b>
    <pre>
    <?php echo strip_tags($this->request->description); ?>
    </pre>
</p>
<h2>Comments:</h2>
<?php foreach($this->comments as $comment):?>
    <p>
        <?php echo $comment->post_date; ?>, <b><?php echo $comment->client_name; ?></b>: <pre style="background:#ccc;padding:5px;"><?php echo strip_tags($comment->text); ?></pre>
    </p>
<?php endforeach; ?>
<hr />

<?php echo $this->form; ?>
