<p><b>State:</b> <?php echo $this->request->state === '0' ? 'Active' : 'Resolved'; ?></p>
<p><b>Description:</b>
    <br />
    <pre>
    <?php echo $this->request->description; ?></pre>
</p>
<h2>Comments:</h2>
<?php foreach($this->comments as $comment):?>
    <p>
        <?php echo $comment->post_date; ?> <b><?php echo $comment->owner_id;//:TODO: ?></b>: <pre style="background:#ccc;padding:5px;"><?php echo $comment->text; ?></pre>
    </p>
<?php endforeach; ?>
<hr />

<?php echo $this->form; ?>
