<?=$this->renderTools($this->tools)?>
<?=$this->renderTabs($this->tabs)?>

<h1>My requests</h1>

<div class="list">
    <?php
        if (count($this->requests) == 0) {
            echo "You have not any active requests.";
        } else { ?>
        <form method="POST">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>#</th>
                    <th>State</th>
                    <th>Description</th>
                </tr>
            </thead>

            <tbody>
            <?php
                $active = "<span class='label label-warning'>Active</span>";
                $resolved = "<span class='label label-success'>Resolved</span>";
                foreach($this->requests as $request) {
                    $state = $request->state === '0' ? $active : $resolved;

                    echo <<<HTML
<tr>
    <td><input type="checkbox" value="{$request->id}" name='chboxList[]'></td>
    <td>{$request->id}</td>
    <td>{$state}</td>
    <td>{$request->description}</td>
</tr>
HTML;
                }?>
            
        </tbody>
        </table>
        <hr />
        <input type='submit' class='btn btn-success' value='Resolve marked'/>
        </form>
    <?php } ?>
</div>
